# Generated by Django 5.1.1 on 2024-10-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_requestlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='expense_type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=6),
        ),
    ]
